name: Artifact Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: echo "Hello from GitHub Actions" > message.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: message-file
          path: message.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: message-file

      - name: Display file
        run: cat message.txt
